---
- name: Install git
  ansible.builtin.apt:
    name: git
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Register git trait in executor traits file
  ansible.builtin.lineinfile:
    path: /etc/cider-ci/traits
    line: "git"
