---
- hosts: cider_ci_executors
  become: yes

  pre_tasks:
    - name: Bootstrap python3 if absent
      raw: test -e /usr/bin/python3 || (apt-get -y update && apt-get install -y python3)
      changed_when: false

  roles:
    - role: common
      tags: [common]

    - role: java
      tags: [java]

    - role: executor
      tags: [executor]

    - role: trait-asdf
      when: ci_executor_trait_asdf | default(false)
      tags: [trait-asdf]

    - role: trait-postgresql
      when: ci_executor_trait_postgresql | default(false)
      tags: [trait-postgresql]

    - role: trait-stress-ng
      when: ci_executor_trait_stress_ng | default(false)
      tags: [trait-stress-ng]

    - role: trait-git
      when: ci_executor_trait_git | default(false)
      tags: [trait-git]
