---
- hosts: cider_ci_executors
  become: yes

  pre_tasks:
    - name: Bootstrap python3 if absent
      raw: test -e /usr/bin/python3 || (apt-get -y update && apt-get install -y python3)
      changed_when: false

  roles:
    - role: common
      tags: [common]

    - role: java
      tags: [java]

    - role: executor
      tags: [executor]
