---
- name: Install stress-ng
  ansible.builtin.apt:
    name: stress-ng
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Register stress-ng trait in executor traits file
  ansible.builtin.lineinfile:
    path: /etc/cider-ci/traits
    line: "stress-ng"
